### PR TITLE
Remove deprecation warning at startup

### LINKED ISSUE #42: Pytest deprecation warnings
Just started using pytest-black and I'm loving it, but I'm getting a bunch of deprecation warnings:
```
============================================================================================================= warnings summary ==============================================================================================================
/usr/local/lib/python3.8/site-packages/pytest_black.py:26: 84 tests with warnings
  /usr/local/lib/python3.8/site-packages/pytest_black.py:26: PytestDeprecationWarning: direct construction of BlackItem has been deprecated, please use BlackItem.from_parent
    return BlackItem(path, parent)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

Requirements.txt:
```
pytest==5.4.1
pytest-black==0.3.8
```

### PR DESCRIPTION
**Pull request by MRigal**
Fixes #42

### CODE REVIEW

**Comment by paddycarey** [comment]
Thanks for the PR! I'll poke Travis to run the tests and should be able to get this merged later tonight or tomorrow.

**Comment by pe224** [comment]
Cool! Hope this lands soon.

For me, I also needed to [adapt the signature here](https://github.com/shopkeep/pytest-black/blob/53bc2891e57c1611e495299384dda597f2605a16/pytest_black.py#L46-L47) to
```python
    def __init__(self, fspath, parent):
        super(BlackItem, self).__init__(fspath, parent)
```

otherwise there was an error.

**Comment by MRigal** [comment]
Thanks @pe224 it was indeed missing! I hope it still works fine with all older versions also, but I can't see or start the Travis jobs... @paddycarey maybe?

**Comment by paddycarey** [comment]
Sorry for the delay, this looks good to me but just having a little trouble with the travis build and required statuses. I can see that it's passed the build fine, but hasn't come through here for some reason.

I'm no longer working at shopkeep so don't have admin access to this repo to just disable the status check and merge, but I've reached out to some folks who do, so should be able to merge soon hopefully.

**Comment by MRigal** [comment]
Thanks @paddycarey ! For all folks from Shopkeep:

Thanks for the nice work so far! In case maintenance of the project might become to heavy, you could consider transferring the plugin to the https://github.com/pytest-dev organization (and/or adding some contributes as maintainers of this repo).

**Comment by paddycarey** [comment]
PR's been merged, i'll get the new version out shortly, thanks!

**Pull request merged**
