### PR TITLE
Remove upperbound for required black version

### PR DESCRIPTION
**Pull request by tdamsma**
As long as there is no reason to restrict the black version I think it should not be pinned

### CODE REVIEW

**Comment by paddycarey** [comment]
This has come up a few times, I _think_ we still need the pin (though happy to be wrong here) because of the way that some tooling treats pre-release versions, see https://github.com/shopkeep/pytest-black/pull/29#issuecomment-482634195 for an explanation

**Comment by wbolster-eiq** [comment]
if an application wants a specific version, it's up to that application to add the right version to its pinned dependencies.

right now it is impossible to use the latest version of `black` with this plugin, which is unfortunate and likely not intentional.

libraries should not pin to specific versions of transitive dependencies at all, since pinning is an _application_ concern, not a library concern.

pipenv compatibility seems a weird reason to me. many projects don't use pipenv at all and it seems to be a dying project anyway.

**Comment by paddycarey** [comment]
OK sure, that makes sense, I'll merge this PR and ship a release as soon as I get the time to do so, should hopefully be later tonight.

**Comment by paddycarey** [comment]
0.3.8 has been release to PyPI, let me know if you have any issues!

**Comment by wbolster-eiq** [comment]
thanks for your work, @paddycarey!

**Comment by lig** [comment]
@wbolster-eiq and many projects do use `pipenv` and with this the only way to go is to pin `pytest-black<0.3.8` :(

**Comment by wbolster-eiq** [comment]
this is a `pytest` plugin for `black`...

and it seems very logical to me that the latest `pytest` and the latest `black` should be able to cooperate out of the box.

tbh, i'm not sure how `pipenv` is related at all. seems like a `pipenv` issue, not an issue for pytest plugin?

**Pull request merged**
